services:
  db:
    image: timescale/timescaledb:latest-pg16
    restart: always
    environment:
      POSTGRES_USER: f1intel
      POSTGRES_PASSWORD: f1intel
      POSTGRES_DB: f1intel
    ports:
      - "5432:5432"
    volumes:
      - "data-db:/var/lib/postgresql/data"

volumes:
  data-db: