spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: jdbc:postgresql://localhost:5432/f1intel
    username: f1intel
    password: f1intel

openf1:
  base-url: https://api.openf1.org/v1